### ISSUE TITLE
Very nice example,but i'm not used pipenv

### ISSUE THREAD

**Issue by bowuL** [adr1enbe4udou1n/fastapi-realworld-example-app#1]
I see you committed new pip.lock 12 hours ago,I have poetry and pip,how about provide a requirement.txt?hah,thanks very much

**Comment by adr1enbe4udou1n** [comment]
You just have to do `pipenv run pip freeze > requirements.txt` for that.

Next actual versions from lock :

```txt
alembic==1.7.6
anyio==3.5.0
asgiref==3.5.0
atomicwrites==1.4.0
attrs==21.4.0
autoflake==1.4
bcrypt==3.2.0
black==22.1.0
certifi==2021.10.8
cffi==1.15.0
charset-normalizer==2.0.11
click==8.0.3
colorama==0.4.4
coverage==6.3.1
cryptography==36.0.1
dnspython==2.2.0
ecdsa==0.18.0b2
email-validator==1.1.3
Faker==12.1.0
fastapi==0.73.0
flake8==4.0.1
greenlet==2.0.0a1
h11==0.13.0
httptools==0.3.0
idna==3.3
iniconfig==1.1.1
isort==5.10.1
Mako==1.1.6
MarkupSafe==2.0.1
mccabe==0.6.1
mypy==0.931
mypy-extensions==0.4.3
packaging==21.3
passlib==1.7.4
pathspec==0.9.0
platformdirs==2.4.1
pluggy==1.0.0
psycopg2-binary==2.9.3
py==1.11.0
pyasn1==0.4.8
pycodestyle==2.8.0
pycparser==2.21
pydantic==1.9.0
pyflakes==2.4.0
pyparsing==3.0.7
pytest==7.0.0
pytest-cov==3.0.0
python-dateutil==2.8.2
python-dotenv==0.19.2
python-jose==3.3.0
python-slugify==5.0.2
PyYAML==6.0
requests==2.27.1
rsa==4.8
six==1.16.0
sniffio==1.2.0
SQLAlchemy==1.4.31
sqlalchemy-stubs==0.4
starlette==0.17.1
text-unidecode==1.3
tomli==2.0.1
types-python-slugify==5.0.3
typing_extensions==4.0.1
urllib3==1.26.8
uvicorn==0.17.4
watchgod==0.7
websockets==10.1
```

**Comment by bowuL** [comment]
> You just have to do `pipenv run pip freeze > requirements.txt` for that.
> 
> Next actual versions from lock :
> 
> ```
> alembic==1.7.6
> anyio==3.5.0
> asgiref==3.5.0
> atomicwrites==1.4.0
> attrs==21.4.0
> autoflake==1.4
> bcrypt==3.2.0
> black==22.1.0
> certifi==2021.10.8
> cffi==1.15.0
> charset-normalizer==2.0.11
> click==8.0.3
> colorama==0.4.4
> coverage==6.3.1
> cryptography==36.0.1
> dnspython==2.2.0
> ecdsa==0.18.0b2
> email-validator==1.1.3
> Faker==12.1.0
> fastapi==0.73.0
> flake8==4.0.1
> greenlet==2.0.0a1
> h11==0.13.0
> httptools==0.3.0
> idna==3.3
> iniconfig==1.1.1
> isort==5.10.1
> Mako==1.1.6
> MarkupSafe==2.0.1
> mccabe==0.6.1
> mypy==0.931
> mypy-extensions==0.4.3
> packaging==21.3
> passlib==1.7.4
> pathspec==0.9.0
> platformdirs==2.4.1
> pluggy==1.0.0
> psycopg2-binary==2.9.3
> py==1.11.0
> pyasn1==0.4.8
> pycodestyle==2.8.0
> pycparser==2.21
> pydantic==1.9.0
> pyflakes==2.4.0
> pyparsing==3.0.7
> pytest==7.0.0
> pytest-cov==3.0.0
> python-dateutil==2.8.2
> python-dotenv==0.19.2
> python-jose==3.3.0
> python-slugify==5.0.2
> PyYAML==6.0
> requests==2.27.1
> rsa==4.8
> six==1.16.0
> sniffio==1.2.0
> SQLAlchemy==1.4.31
> sqlalchemy-stubs==0.4
> starlette==0.17.1
> text-unidecode==1.3
> tomli==2.0.1
> types-python-slugify==5.0.3
> typing_extensions==4.0.1
> urllib3==1.26.8
> uvicorn==0.17.4
> watchgod==0.7
> websockets==10.1
> ```

Sorry, i read this reply just now,and i had try to use pipenv, it's a very good practice, thank u very much.
But I get a problem now, I'm using mysql database instead of postgresql, and when i run migrate,it show me error `sqlalchemy.exc.CompileError: (in table 'tags', column 'name'): VARCHAR requires a length on dialect mysql
`, and i change `Column(String)`  to `Column(String(64))`,but still error.Have u tried it?

**Comment by bowuL** [comment]
Sorry, it's my mistake, I need to generate new migrations.
